steps:

- id: go_version
  name: golang
  args: ["go", "version"]

- id: go_build
  name: golang
  args: ['go', 'build', '-o', 'myiac', 'github.com/dfernandezm/myiac/app']
  env: ['GO111MODULE=on']

artifacts:
  objects:
    location: 'gs://myiac-base/'
    paths: ['myiac', 'helperScripts']

