name: Build Docker Image

on:
  push:
    branches: [ docker/* ]
  pull_request:
    branches: [ master ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      TERRAFORM_V: 1.0.3
      HELM_V: 3.5.2
      KUBE_PROMPT_V: 1.0.11
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build docker image
        run: |
          docker build -t polinux/myiac:latest \
            --build-arg CURRENT_HELM_VERSION=$HELM_V \
            --build-arg CURRENT_TERRAFORM_VERSION=$TERRAFORM_V \
            --build-arg CURRENT_KUBE_PROMPT_VERSION=$KUBE_PROMPT_V \
          -f Dockerfiles/Dockerfile .

      - name: Test Image
        run: |
          docker run -i --rm polinux/myiac:latest myiac --help
          docker run -i --rm polinux/myiac:latest terraform version
          docker run -i --rm polinux/myiac:latest helm version
          docker run -i --rm polinux/myiac:latest gcloud version
          docker run -i --rm polinux/myiac:latest helm diff --help

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Stage image
        run: |
          docker tag polinux/myiac:latest polinux/myiac:stage
          docker push polinux/myiac:stage